// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  CreateHostedZoneData,
  CreateHostedZoneErrors,
  CreateHostedZoneResponses,
  CreateRecordData,
  CreateRecordErrors,
  CreateRecordResponses,
  DeleteHostedZoneData,
  DeleteHostedZoneErrors,
  DeleteHostedZoneResponses,
  DeleteRecordData,
  DeleteRecordErrors,
  DeleteRecordResponses,
  GetHostedZoneData,
  GetHostedZoneErrors,
  GetHostedZoneResponses,
  GetRecordData,
  GetRecordErrors,
  GetRecordResponses,
  HealthzData,
  HealthzResponses,
  ListHostedZonesData,
  ListHostedZonesErrors,
  ListHostedZonesResponses,
  ListRecordsData,
  ListRecordsErrors,
  ListRecordsResponses,
  LoginData,
  LoginErrors,
  LoginResponses,
  LogoutData,
  LogoutResponses,
  ReadCurrentUserData,
  ReadCurrentUserErrors,
  ReadCurrentUserResponses,
  ReplaceRecordData,
  ReplaceRecordErrors,
  ReplaceRecordResponses,
  UpdateHostedZoneData,
  UpdateHostedZoneErrors,
  UpdateHostedZoneResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Sign in
 *
 * Verifies credentials and opens a session. On success the response sets an httpOnly session cookie and a readable CSRF cookie; echo the returned CSRF token in the X-CSRF-Token header on every subsequent write.
 */
export const login = <ThrowOnError extends boolean = false>(
  options: Options<LoginData, ThrowOnError>,
): RequestResult<LoginResponses, LoginErrors, ThrowOnError> =>
  (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: "/api/v1/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Sign out
 *
 * Deletes the session row and clears both cookies.
 */
export const logout = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutData, ThrowOnError>,
): RequestResult<LogoutResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({
    url: "/api/v1/auth/logout",
    ...options,
  });

/**
 * Current user
 *
 * Returns the signed-in account. The frontend calls this on load to decide whether a stored cookie still represents a live session.
 */
export const readCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<ReadCurrentUserData, ThrowOnError>,
): RequestResult<
  ReadCurrentUserResponses,
  ReadCurrentUserErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ReadCurrentUserResponses,
    ReadCurrentUserErrors,
    ThrowOnError
  >({ url: "/api/v1/auth/me", ...options });

/**
 * List hosted zones
 *
 * Returns the signed-in user's hosted zones. Sorting is restricted to an allowlist of columns, so no client value ever reaches the ORDER BY clause unvalidated.
 */
export const listHostedZones = <ThrowOnError extends boolean = false>(
  options?: Options<ListHostedZonesData, ThrowOnError>,
): RequestResult<
  ListHostedZonesResponses,
  ListHostedZonesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListHostedZonesResponses,
    ListHostedZonesErrors,
    ThrowOnError
  >({ url: "/api/v1/hosted-zones", ...options });

/**
 * Create a hosted zone
 *
 * Creates a zone together with its generated SOA record and apex NS record listing four name servers, in one transaction. Both are read-only afterwards.
 */
export const createHostedZone = <ThrowOnError extends boolean = false>(
  options: Options<CreateHostedZoneData, ThrowOnError>,
): RequestResult<
  CreateHostedZoneResponses,
  CreateHostedZoneErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateHostedZoneResponses,
    CreateHostedZoneErrors,
    ThrowOnError
  >({
    url: "/api/v1/hosted-zones",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a hosted zone
 *
 * Deletes a zone that holds no records beyond its generated SOA and NS. Delete the remaining records first.
 */
export const deleteHostedZone = <ThrowOnError extends boolean = false>(
  options: Options<DeleteHostedZoneData, ThrowOnError>,
): RequestResult<
  DeleteHostedZoneResponses,
  DeleteHostedZoneErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteHostedZoneResponses,
    DeleteHostedZoneErrors,
    ThrowOnError
  >({ url: "/api/v1/hosted-zones/{zone_id}", ...options });

/**
 * Get a hosted zone
 *
 * Returns one zone. A zone owned by another user produces 404 rather than 403, because 403 would confirm that the identifier exists.
 */
export const getHostedZone = <ThrowOnError extends boolean = false>(
  options: Options<GetHostedZoneData, ThrowOnError>,
): RequestResult<GetHostedZoneResponses, GetHostedZoneErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetHostedZoneResponses,
    GetHostedZoneErrors,
    ThrowOnError
  >({ url: "/api/v1/hosted-zones/{zone_id}", ...options });

/**
 * Update a hosted zone
 *
 * Updates the description. A zone's name is immutable.
 */
export const updateHostedZone = <ThrowOnError extends boolean = false>(
  options: Options<UpdateHostedZoneData, ThrowOnError>,
): RequestResult<
  UpdateHostedZoneResponses,
  UpdateHostedZoneErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UpdateHostedZoneResponses,
    UpdateHostedZoneErrors,
    ThrowOnError
  >({
    url: "/api/v1/hosted-zones/{zone_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List records in a hosted zone
 *
 * Returns the zone's record sets, including the generated SOA and NS records, which are flagged with `is_system`.
 */
export const listRecords = <ThrowOnError extends boolean = false>(
  options: Options<ListRecordsData, ThrowOnError>,
): RequestResult<ListRecordsResponses, ListRecordsErrors, ThrowOnError> =>
  (options.client ?? client).get<
    ListRecordsResponses,
    ListRecordsErrors,
    ThrowOnError
  >({ url: "/api/v1/hosted-zones/{zone_id}/records", ...options });

/**
 * Create a record set
 *
 * Creates a record set. The body is discriminated on `type`, so each record type documents its own value format and cardinality. A relative `name` such as `www` or `@` is qualified against the zone.
 */
export const createRecord = <ThrowOnError extends boolean = false>(
  options: Options<CreateRecordData, ThrowOnError>,
): RequestResult<CreateRecordResponses, CreateRecordErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateRecordResponses,
    CreateRecordErrors,
    ThrowOnError
  >({
    url: "/api/v1/hosted-zones/{zone_id}/records",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a record set
 *
 * Deletes a record set. The zone's generated SOA and NS records cannot be removed.
 */
export const deleteRecord = <ThrowOnError extends boolean = false>(
  options: Options<DeleteRecordData, ThrowOnError>,
): RequestResult<DeleteRecordResponses, DeleteRecordErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteRecordResponses,
    DeleteRecordErrors,
    ThrowOnError
  >({ url: "/api/v1/hosted-zones/{zone_id}/records/{record_id}", ...options });

/**
 * Get a record set
 *
 * Return one record set.
 */
export const getRecord = <ThrowOnError extends boolean = false>(
  options: Options<GetRecordData, ThrowOnError>,
): RequestResult<GetRecordResponses, GetRecordErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetRecordResponses,
    GetRecordErrors,
    ThrowOnError
  >({ url: "/api/v1/hosted-zones/{zone_id}/records/{record_id}", ...options });

/**
 * Replace a record set
 *
 * Replaces a record set's name, type, TTL, and values. The zone's generated SOA and NS records are rejected with 409.
 */
export const replaceRecord = <ThrowOnError extends boolean = false>(
  options: Options<ReplaceRecordData, ThrowOnError>,
): RequestResult<ReplaceRecordResponses, ReplaceRecordErrors, ThrowOnError> =>
  (options.client ?? client).put<
    ReplaceRecordResponses,
    ReplaceRecordErrors,
    ThrowOnError
  >({
    url: "/api/v1/hosted-zones/{zone_id}/records/{record_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Health check
 *
 * Report readiness, including a database round trip.
 */
export const healthz = <ThrowOnError extends boolean = false>(
  options?: Options<HealthzData, ThrowOnError>,
): RequestResult<HealthzResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<HealthzResponses, unknown, ThrowOnError>({
    url: "/healthz",
    ...options,
  });
