// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AAAARecord
 *
 * IPv6 address record.
 */
export type AaaaRecord = {
  /**
   * Name
   *
   * Record name. Relative names are qualified with the zone name.
   */
  name: string;
  /**
   * Ttl
   */
  ttl?: number;
  /**
   * Routing Policy
   */
  routing_policy?:
    "Simple" | "Weighted" | "Latency" | "Failover" | "Multivalue";
  /**
   * Set Identifier
   *
   * Distinguishes record sets sharing a name and type. Simple routing omits it.
   */
  set_identifier?: string | null;
  /**
   * Values
   */
  values: Array<string>;
  /**
   * Type
   */
  type: "AAAA";
};

/**
 * ARecord
 *
 * IPv4 address record.
 */
export type ARecord = {
  /**
   * Name
   *
   * Record name. Relative names are qualified with the zone name.
   */
  name: string;
  /**
   * Ttl
   */
  ttl?: number;
  /**
   * Routing Policy
   */
  routing_policy?:
    "Simple" | "Weighted" | "Latency" | "Failover" | "Multivalue";
  /**
   * Set Identifier
   *
   * Distinguishes record sets sharing a name and type. Simple routing omits it.
   */
  set_identifier?: string | null;
  /**
   * Values
   */
  values: Array<string>;
  /**
   * Type
   */
  type: "A";
};

/**
 * Body_import_zone_file
 */
export type BodyImportZoneFile = {
  /**
   * File
   *
   * A BIND master file.
   */
  file: Blob | File;
};

/**
 * BulkDeleteRequest
 *
 * Body of the bulk record delete.
 */
export type BulkDeleteRequest = {
  /**
   * Record Ids
   *
   * Record identifiers to delete. Generated records are refused.
   */
  record_ids: Array<string>;
};

/**
 * BulkDeleteResponse
 *
 * The outcome of a bulk delete.
 */
export type BulkDeleteResponse = {
  /**
   * Deleted
   *
   * Record sets removed.
   */
  deleted: number;
  /**
   * Refused
   *
   * Identifiers that were not removed, because they are generated system records or do not exist.
   */
  refused: Array<string>;
};

/**
 * CAARecord
 *
 * Certification authority authorization record.
 */
export type CaaRecord = {
  /**
   * Name
   *
   * Record name. Relative names are qualified with the zone name.
   */
  name: string;
  /**
   * Ttl
   */
  ttl?: number;
  /**
   * Routing Policy
   */
  routing_policy?:
    "Simple" | "Weighted" | "Latency" | "Failover" | "Multivalue";
  /**
   * Set Identifier
   *
   * Distinguishes record sets sharing a name and type. Simple routing omits it.
   */
  set_identifier?: string | null;
  /**
   * Values
   */
  values: Array<string>;
  /**
   * Type
   */
  type: "CAA";
};

/**
 * CNAMERecord
 *
 * Canonical name record.
 *
 * Single-valued by protocol, and additionally barred from the zone apex and
 * from coexisting with any sibling — both enforced in the service layer,
 * because they depend on what else the zone already contains.
 */
export type CnameRecord = {
  /**
   * Name
   *
   * Record name. Relative names are qualified with the zone name.
   */
  name: string;
  /**
   * Ttl
   */
  ttl?: number;
  /**
   * Routing Policy
   */
  routing_policy?:
    "Simple" | "Weighted" | "Latency" | "Failover" | "Multivalue";
  /**
   * Set Identifier
   *
   * Distinguishes record sets sharing a name and type. Simple routing omits it.
   */
  set_identifier?: string | null;
  /**
   * Values
   */
  values: [string];
  /**
   * Type
   */
  type: "CNAME";
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * HostedZoneCreate
 *
 * Body of `POST /hosted-zones`.
 *
 * Omits `public_id`, `user_id`, `record_count`, and `created_by`. A client
 * cannot set ownership or forge a zone identifier because those fields have no
 * representation in the input type.
 */
export type HostedZoneCreate = {
  /**
   * Name
   *
   * Domain name for the zone.
   */
  name: string;
  /**
   * Comment
   *
   * Shown as 'Description' in the console.
   */
  comment?: string | null;
  /**
   * Type
   */
  type?: "Public" | "Private";
};

/**
 * HostedZoneResponse
 *
 * A hosted zone as returned by the API.
 */
export type HostedZoneResponse = {
  /**
   * Id
   *
   * Route 53-style zone identifier.
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Type
   */
  type: "Public" | "Private";
  /**
   * Comment
   */
  comment: string | null;
  /**
   * Record Count
   */
  record_count: number;
  /**
   * Created By
   */
  created_by: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string | null;
};

/**
 * HostedZoneUpdate
 *
 * Body of `PATCH /hosted-zones/{public_id}`.
 *
 * Only the description is mutable. A zone's name is its identity, and renaming
 * one would silently orphan every record beneath it.
 */
export type HostedZoneUpdate = {
  /**
   * Comment
   */
  comment?: string | null;
};

/**
 * ImportResponse
 *
 * The outcome of a zone-file import.
 */
export type ImportResponse = {
  /**
   * Created
   *
   * Record sets created.
   */
  created: number;
  /**
   * Skipped
   *
   * Records that were not created, each with a reason.
   */
  skipped: Array<SkippedLineResponse>;
};

/**
 * LoginRequest
 *
 * Credentials submitted to `POST /auth/login`.
 */
export type LoginRequest = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
};

/**
 * LoginResponse
 *
 * Returned on successful login, alongside the session cookie.
 */
export type LoginResponse = {
  user: UserResponse;
  /**
   * Csrf Token
   *
   * Echo this in the X-CSRF-Token header on state-changing requests.
   */
  csrf_token: string;
};

/**
 * MXRecord
 *
 * Mail exchanger record.
 */
export type MxRecord = {
  /**
   * Name
   *
   * Record name. Relative names are qualified with the zone name.
   */
  name: string;
  /**
   * Ttl
   */
  ttl?: number;
  /**
   * Routing Policy
   */
  routing_policy?:
    "Simple" | "Weighted" | "Latency" | "Failover" | "Multivalue";
  /**
   * Set Identifier
   *
   * Distinguishes record sets sharing a name and type. Simple routing omits it.
   */
  set_identifier?: string | null;
  /**
   * Values
   */
  values: Array<string>;
  /**
   * Type
   */
  type: "MX";
};

/**
 * NSRecord
 *
 * Name server record.
 */
export type NsRecord = {
  /**
   * Name
   *
   * Record name. Relative names are qualified with the zone name.
   */
  name: string;
  /**
   * Ttl
   */
  ttl?: number;
  /**
   * Routing Policy
   */
  routing_policy?:
    "Simple" | "Weighted" | "Latency" | "Failover" | "Multivalue";
  /**
   * Set Identifier
   *
   * Distinguishes record sets sharing a name and type. Simple routing omits it.
   */
  set_identifier?: string | null;
  /**
   * Values
   */
  values: Array<string>;
  /**
   * Type
   */
  type: "NS";
};

/**
 * PTRRecord
 *
 * Pointer record.
 */
export type PtrRecord = {
  /**
   * Name
   *
   * Record name. Relative names are qualified with the zone name.
   */
  name: string;
  /**
   * Ttl
   */
  ttl?: number;
  /**
   * Routing Policy
   */
  routing_policy?:
    "Simple" | "Weighted" | "Latency" | "Failover" | "Multivalue";
  /**
   * Set Identifier
   *
   * Distinguishes record sets sharing a name and type. Simple routing omits it.
   */
  set_identifier?: string | null;
  /**
   * Values
   */
  values: [string];
  /**
   * Type
   */
  type: "PTR";
};

/**
 * Page[HostedZoneResponse]
 */
export type PageHostedZoneResponse = {
  /**
   * Items
   */
  items: Array<HostedZoneResponse>;
  /**
   * Total
   *
   * Total rows matching the filter, ignoring pagination.
   */
  total: number;
  /**
   * Next Token
   *
   * Offset to pass as `offset` for the next page, or null on the last page.
   */
  next_token?: string | null;
};

/**
 * Page[RecordSetResponse]
 */
export type PageRecordSetResponse = {
  /**
   * Items
   */
  items: Array<RecordSetResponse>;
  /**
   * Total
   *
   * Total rows matching the filter, ignoring pagination.
   */
  total: number;
  /**
   * Next Token
   *
   * Offset to pass as `offset` for the next page, or null on the last page.
   */
  next_token?: string | null;
};

/**
 * ProblemDetail
 *
 * An RFC 9457 error body.
 *
 * Declared so it appears in the OpenAPI schema and therefore in the generated
 * TypeScript client, giving the frontend a typed error shape.
 */
export type ProblemDetail = {
  /**
   * Type
   *
   * Stable slug identifying the error class.
   */
  type: string;
  /**
   * Title
   */
  title: string;
  /**
   * Status
   */
  status: number;
  /**
   * Detail
   *
   * Human-readable explanation, safe to display.
   */
  detail: string;
  /**
   * Instance
   *
   * Path of the request that failed.
   */
  instance: string;
  /**
   * Correlation Id
   *
   * Quote this when reporting a failure.
   */
  correlation_id: string;
};

/**
 * RecordSetResponse
 *
 * A record set as returned by the API.
 *
 * Built explicitly by the router rather than from the ORM object, because
 * `values` has to be flattened out of the child table into a list of strings.
 */
export type RecordSetResponse = {
  /**
   * Id
   *
   * Opaque record identifier.
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Type
   */
  type: string;
  /**
   * Ttl
   */
  ttl: number;
  /**
   * Routing Policy
   */
  routing_policy: string;
  /**
   * Set Identifier
   */
  set_identifier: string | null;
  /**
   * Values
   */
  values: Array<string>;
  /**
   * Is System
   *
   * True for the zone's generated SOA and apex NS records, which cannot be edited or deleted.
   */
  is_system: boolean;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string | null;
};

/**
 * RecordSortField
 *
 * Columns a record listing may be sorted by.
 */
export type RecordSortField = "name" | "type" | "ttl";

/**
 * SRVRecord
 *
 * Service locator record.
 */
export type SrvRecord = {
  /**
   * Name
   *
   * Record name. Relative names are qualified with the zone name.
   */
  name: string;
  /**
   * Ttl
   */
  ttl?: number;
  /**
   * Routing Policy
   */
  routing_policy?:
    "Simple" | "Weighted" | "Latency" | "Failover" | "Multivalue";
  /**
   * Set Identifier
   *
   * Distinguishes record sets sharing a name and type. Simple routing omits it.
   */
  set_identifier?: string | null;
  /**
   * Values
   */
  values: Array<string>;
  /**
   * Type
   */
  type: "SRV";
};

/**
 * SkippedLineResponse
 *
 * One record the importer declined, and why.
 */
export type SkippedLineResponse = {
  /**
   * Line
   *
   * Source line number, or 0 for a whole-record rejection.
   */
  line: number;
  /**
   * Text
   *
   * The offending line, truncated.
   */
  text: string;
  /**
   * Reason
   *
   * Why it was skipped, safe to show the user.
   */
  reason: string;
};

/**
 * SortOrder
 *
 * Sort direction accepted by list endpoints.
 */
export type SortOrder = "asc" | "desc";

/**
 * TXTRecord
 *
 * Text record holding one or more quoted character-strings.
 */
export type TxtRecord = {
  /**
   * Name
   *
   * Record name. Relative names are qualified with the zone name.
   */
  name: string;
  /**
   * Ttl
   */
  ttl?: number;
  /**
   * Routing Policy
   */
  routing_policy?:
    "Simple" | "Weighted" | "Latency" | "Failover" | "Multivalue";
  /**
   * Set Identifier
   *
   * Distinguishes record sets sharing a name and type. Simple routing omits it.
   */
  set_identifier?: string | null;
  /**
   * Values
   */
  values: Array<string>;
  /**
   * Type
   */
  type: "TXT";
};

/**
 * UserResponse
 *
 * The authenticated account.
 *
 * `password_hash` is absent by construction: it is not a field here, so no
 * change to the ORM model can leak it through this response.
 */
export type UserResponse = {
  /**
   * Email
   */
  email: string;
  /**
   * Created At
   */
  created_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

/**
 * ZoneSortField
 *
 * Columns a hosted-zone listing may be sorted by.
 *
 * An enum rather than a free string: `sort` reaches the ORDER BY clause, so an
 * unvalidated value is the one genuine SQL-injection surface in the API.
 */
export type ZoneSortField = "name" | "type" | "record_count" | "created_at";

export type LoginData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: "/api/v1/auth/login";
};

export type LoginErrors = {
  /**
   * Email or password incorrect.
   */
  401: ProblemDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
  /**
   * Too many attempts from this address.
   */
  429: ProblemDetail;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
  /**
   * Successful Response
   */
  200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type LogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/logout";
};

export type LogoutResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type ReadCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/me";
};

export type ReadCurrentUserErrors = {
  /**
   * No valid session.
   */
  401: ProblemDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadCurrentUserError =
  ReadCurrentUserErrors[keyof ReadCurrentUserErrors];

export type ReadCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type ReadCurrentUserResponse =
  ReadCurrentUserResponses[keyof ReadCurrentUserResponses];

export type ListHostedZonesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Search
     *
     * Substring of the name.
     */
    search?: string | null;
    sort?: ZoneSortField;
    order?: SortOrder;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Offset
     */
    offset?: number;
  };
  url: "/api/v1/hosted-zones";
};

export type ListHostedZonesErrors = {
  /**
   * No valid session cookie was presented.
   */
  401: ProblemDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListHostedZonesError =
  ListHostedZonesErrors[keyof ListHostedZonesErrors];

export type ListHostedZonesResponses = {
  /**
   * Successful Response
   */
  200: PageHostedZoneResponse;
};

export type ListHostedZonesResponse =
  ListHostedZonesResponses[keyof ListHostedZonesResponses];

export type CreateHostedZoneData = {
  body: HostedZoneCreate;
  headers?: {
    /**
     * X-Csrf-Token
     */
    "X-CSRF-Token"?: string | null;
  };
  path?: never;
  query?: never;
  url: "/api/v1/hosted-zones";
};

export type CreateHostedZoneErrors = {
  /**
   * No valid session cookie was presented.
   */
  401: ProblemDetail;
  /**
   * You already have a zone with this name.
   */
  409: ProblemDetail;
  /**
   * Failed validation.
   */
  422: ProblemDetail;
};

export type CreateHostedZoneError =
  CreateHostedZoneErrors[keyof CreateHostedZoneErrors];

export type CreateHostedZoneResponses = {
  /**
   * Successful Response
   */
  201: HostedZoneResponse;
};

export type CreateHostedZoneResponse =
  CreateHostedZoneResponses[keyof CreateHostedZoneResponses];

export type DeleteHostedZoneData = {
  body?: never;
  headers?: {
    /**
     * X-Csrf-Token
     */
    "X-CSRF-Token"?: string | null;
  };
  path: {
    /**
     * Zone Id
     */
    zone_id: string;
  };
  query?: never;
  url: "/api/v1/hosted-zones/{zone_id}";
};

export type DeleteHostedZoneErrors = {
  /**
   * No valid session cookie was presented.
   */
  401: ProblemDetail;
  /**
   * Not found, or owned by another user.
   */
  404: ProblemDetail;
  /**
   * The zone still contains records.
   */
  409: ProblemDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteHostedZoneError =
  DeleteHostedZoneErrors[keyof DeleteHostedZoneErrors];

export type DeleteHostedZoneResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteHostedZoneResponse =
  DeleteHostedZoneResponses[keyof DeleteHostedZoneResponses];

export type GetHostedZoneData = {
  body?: never;
  path: {
    /**
     * Zone Id
     */
    zone_id: string;
  };
  query?: never;
  url: "/api/v1/hosted-zones/{zone_id}";
};

export type GetHostedZoneErrors = {
  /**
   * No valid session cookie was presented.
   */
  401: ProblemDetail;
  /**
   * Not found, or owned by another user.
   */
  404: ProblemDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetHostedZoneError = GetHostedZoneErrors[keyof GetHostedZoneErrors];

export type GetHostedZoneResponses = {
  /**
   * Successful Response
   */
  200: HostedZoneResponse;
};

export type GetHostedZoneResponse =
  GetHostedZoneResponses[keyof GetHostedZoneResponses];

export type UpdateHostedZoneData = {
  body: HostedZoneUpdate;
  headers?: {
    /**
     * X-Csrf-Token
     */
    "X-CSRF-Token"?: string | null;
  };
  path: {
    /**
     * Zone Id
     */
    zone_id: string;
  };
  query?: never;
  url: "/api/v1/hosted-zones/{zone_id}";
};

export type UpdateHostedZoneErrors = {
  /**
   * No valid session cookie was presented.
   */
  401: ProblemDetail;
  /**
   * Not found, or owned by another user.
   */
  404: ProblemDetail;
  /**
   * Failed validation.
   */
  422: ProblemDetail;
};

export type UpdateHostedZoneError =
  UpdateHostedZoneErrors[keyof UpdateHostedZoneErrors];

export type UpdateHostedZoneResponses = {
  /**
   * Successful Response
   */
  200: HostedZoneResponse;
};

export type UpdateHostedZoneResponse =
  UpdateHostedZoneResponses[keyof UpdateHostedZoneResponses];

export type ListRecordsData = {
  body?: never;
  path: {
    /**
     * Zone Id
     */
    zone_id: string;
  };
  query?: {
    /**
     * Search
     */
    search?: string | null;
    /**
     * Type
     *
     * Filter to one record type.
     */
    type?: string | null;
    sort?: RecordSortField;
    order?: SortOrder;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Offset
     */
    offset?: number;
  };
  url: "/api/v1/hosted-zones/{zone_id}/records";
};

export type ListRecordsErrors = {
  /**
   * No valid session cookie was presented.
   */
  401: ProblemDetail;
  /**
   * Not found, or owned by another user.
   */
  404: ProblemDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListRecordsError = ListRecordsErrors[keyof ListRecordsErrors];

export type ListRecordsResponses = {
  /**
   * Successful Response
   */
  200: PageRecordSetResponse;
};

export type ListRecordsResponse =
  ListRecordsResponses[keyof ListRecordsResponses];

export type CreateRecordData = {
  /**
   * Payload
   */
  body:
    | ARecord
    | AaaaRecord
    | CnameRecord
    | TxtRecord
    | MxRecord
    | NsRecord
    | PtrRecord
    | SrvRecord
    | CaaRecord;
  headers?: {
    /**
     * X-Csrf-Token
     */
    "X-CSRF-Token"?: string | null;
  };
  path: {
    /**
     * Zone Id
     */
    zone_id: string;
  };
  query?: never;
  url: "/api/v1/hosted-zones/{zone_id}/records";
};

export type CreateRecordErrors = {
  /**
   * No valid session cookie was presented.
   */
  401: ProblemDetail;
  /**
   * Not found, or owned by another user.
   */
  404: ProblemDetail;
  /**
   * Duplicate record set, a CNAME sharing a name with another record, or a CNAME at the zone apex.
   */
  409: ProblemDetail;
  /**
   * Failed validation.
   */
  422: ProblemDetail;
};

export type CreateRecordError = CreateRecordErrors[keyof CreateRecordErrors];

export type CreateRecordResponses = {
  /**
   * Successful Response
   */
  201: RecordSetResponse;
};

export type CreateRecordResponse =
  CreateRecordResponses[keyof CreateRecordResponses];

export type BulkDeleteRecordsData = {
  body: BulkDeleteRequest;
  headers?: {
    /**
     * X-Csrf-Token
     */
    "X-CSRF-Token"?: string | null;
  };
  path: {
    /**
     * Zone Id
     */
    zone_id: string;
  };
  query?: never;
  url: "/api/v1/hosted-zones/{zone_id}/records/bulk-delete";
};

export type BulkDeleteRecordsErrors = {
  /**
   * No valid session cookie was presented.
   */
  401: ProblemDetail;
  /**
   * Not found, or owned by another user.
   */
  404: ProblemDetail;
  /**
   * Failed validation.
   */
  422: ProblemDetail;
};

export type BulkDeleteRecordsError =
  BulkDeleteRecordsErrors[keyof BulkDeleteRecordsErrors];

export type BulkDeleteRecordsResponses = {
  /**
   * Successful Response
   */
  200: BulkDeleteResponse;
};

export type BulkDeleteRecordsResponse =
  BulkDeleteRecordsResponses[keyof BulkDeleteRecordsResponses];

export type DeleteRecordData = {
  body?: never;
  headers?: {
    /**
     * X-Csrf-Token
     */
    "X-CSRF-Token"?: string | null;
  };
  path: {
    /**
     * Zone Id
     */
    zone_id: string;
    /**
     * Record Id
     */
    record_id: string;
  };
  query?: never;
  url: "/api/v1/hosted-zones/{zone_id}/records/{record_id}";
};

export type DeleteRecordErrors = {
  /**
   * No valid session cookie was presented.
   */
  401: ProblemDetail;
  /**
   * Not found, or owned by another user.
   */
  404: ProblemDetail;
  /**
   * The record is a generated system record.
   */
  409: ProblemDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteRecordError = DeleteRecordErrors[keyof DeleteRecordErrors];

export type DeleteRecordResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteRecordResponse =
  DeleteRecordResponses[keyof DeleteRecordResponses];

export type GetRecordData = {
  body?: never;
  path: {
    /**
     * Zone Id
     */
    zone_id: string;
    /**
     * Record Id
     */
    record_id: string;
  };
  query?: never;
  url: "/api/v1/hosted-zones/{zone_id}/records/{record_id}";
};

export type GetRecordErrors = {
  /**
   * No valid session cookie was presented.
   */
  401: ProblemDetail;
  /**
   * Not found, or owned by another user.
   */
  404: ProblemDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetRecordError = GetRecordErrors[keyof GetRecordErrors];

export type GetRecordResponses = {
  /**
   * Successful Response
   */
  200: RecordSetResponse;
};

export type GetRecordResponse = GetRecordResponses[keyof GetRecordResponses];

export type ReplaceRecordData = {
  /**
   * Payload
   */
  body:
    | ARecord
    | AaaaRecord
    | CnameRecord
    | TxtRecord
    | MxRecord
    | NsRecord
    | PtrRecord
    | SrvRecord
    | CaaRecord;
  headers?: {
    /**
     * X-Csrf-Token
     */
    "X-CSRF-Token"?: string | null;
  };
  path: {
    /**
     * Zone Id
     */
    zone_id: string;
    /**
     * Record Id
     */
    record_id: string;
  };
  query?: never;
  url: "/api/v1/hosted-zones/{zone_id}/records/{record_id}";
};

export type ReplaceRecordErrors = {
  /**
   * No valid session cookie was presented.
   */
  401: ProblemDetail;
  /**
   * Not found, or owned by another user.
   */
  404: ProblemDetail;
  /**
   * Conflicts with another record, or the target is a system record.
   */
  409: ProblemDetail;
  /**
   * Failed validation.
   */
  422: ProblemDetail;
};

export type ReplaceRecordError = ReplaceRecordErrors[keyof ReplaceRecordErrors];

export type ReplaceRecordResponses = {
  /**
   * Successful Response
   */
  200: RecordSetResponse;
};

export type ReplaceRecordResponse =
  ReplaceRecordResponses[keyof ReplaceRecordResponses];

export type ImportZoneFileData = {
  body: BodyImportZoneFile;
  headers?: {
    /**
     * X-Csrf-Token
     */
    "X-CSRF-Token"?: string | null;
  };
  path: {
    /**
     * Zone Id
     */
    zone_id: string;
  };
  query?: never;
  url: "/api/v1/hosted-zones/{zone_id}/import";
};

export type ImportZoneFileErrors = {
  /**
   * No valid session cookie was presented.
   */
  401: ProblemDetail;
  /**
   * Not found, or owned by another user.
   */
  404: ProblemDetail;
  /**
   * Unreadable, oversized, or unsafe file.
   */
  422: ProblemDetail;
};

export type ImportZoneFileError =
  ImportZoneFileErrors[keyof ImportZoneFileErrors];

export type ImportZoneFileResponses = {
  /**
   * Successful Response
   */
  200: ImportResponse;
};

export type ImportZoneFileResponse =
  ImportZoneFileResponses[keyof ImportZoneFileResponses];

export type ExportZoneData = {
  body?: never;
  path: {
    /**
     * Zone Id
     */
    zone_id: string;
  };
  query?: {
    /**
     * Format
     *
     * Output format.
     */
    format?: "bind" | "json";
  };
  url: "/api/v1/hosted-zones/{zone_id}/export";
};

export type ExportZoneErrors = {
  /**
   * No valid session cookie was presented.
   */
  401: ProblemDetail;
  /**
   * Not found, or owned by another user.
   */
  404: ProblemDetail;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ExportZoneError = ExportZoneErrors[keyof ExportZoneErrors];

export type ExportZoneResponses = {
  /**
   * The zone as a downloadable file.
   */
  200: unknown;
};

export type HealthzData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/healthz";
};

export type HealthzResponses = {
  /**
   * Response Healthz
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type HealthzResponse = HealthzResponses[keyof HealthzResponses];
