'use client';

import {
  Download,
  FileUp,
  Lock,
  Pencil,
  Plus,
  Trash2,
  Upload,
} from 'lucide-react';
import { useState } from 'react';

import { EmptyState } from '@/components/feedback/EmptyState';
import { DeleteRecordModal } from '@/components/records/DeleteRecordModal';
import { ImportZoneFileModal } from '@/components/records/ImportZoneFileModal';
import { RecordFormPanel } from '@/components/records/RecordFormPanel';
import { DataTable, type Column } from '@/components/tables/DataTable';
import { Badge, RecordTypeBadge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { Menu, Tooltip } from '@/components/ui/Menu';
import { Modal } from '@/components/ui/Modal';
import { SearchInput } from '@/components/ui/SearchInput';
import { Select } from '@/components/ui/Select';
import type { HostedZoneResponse, RecordSetResponse } from '@/lib/api/types.gen';
import { useRecords } from '@/lib/queries/records';
import { downloadZoneExport, useBulkDeleteRecords } from '@/lib/queries/zone-files';
import { RECORD_TYPES } from '@/lib/schemas/record';
import { useIsCompact, useIsPhone } from '@/lib/useMediaQuery';
import { useTableState } from '@/lib/useTableState';

const DEFAULT_RECORD_COLUMNS = ['name', 'type', 'routing_policy', 'values', 'ttl'];

/**
 * Columns kept as the viewport narrows, in descending order of usefulness.
 *
 * A record is identified by its name and type, and its value is the reason
 * anyone opened the table — so those three survive on a phone.
 */
const PHONE_COLUMNS = ['name', 'type', 'values'];
const TABLET_COLUMNS = ['name', 'type', 'values', 'ttl'];

/** The records table for one hosted zone. */
export function RecordTable({ zone }: { zone: HostedZoneResponse }) {
  const state = useTableState({
    defaultSort: 'name',
    defaultColumns: DEFAULT_RECORD_COLUMNS,
  });
  const isPhone = useIsPhone();
  const isCompact = useIsCompact();

  const [typeFilter, setTypeFilter] = useState<string>('');
  const [selected, setSelected] = useState<RecordSetResponse[]>([]);
  const [deleting, setDeleting] = useState<RecordSetResponse | null>(null);
  const [bulkDeleting, setBulkDeleting] = useState(false);
  const [editing, setEditing] = useState<RecordSetResponse | null>(null);
  const [creating, setCreating] = useState(false);
  const [importing, setImporting] = useState(false);
  const bulkDelete = useBulkDeleteRecords(zone.id);

  const query = useRecords(zone.id, {
    search: state.search || undefined,
    type: typeFilter || undefined,
    sort: state.sort as 'name' | 'type' | 'ttl',
    order: state.order,
    limit: state.pageSize,
    offset: (state.page - 1) * state.pageSize,
  });

  const records = query.data?.items ?? [];
  const total = query.data?.total ?? 0;
  const selectedRecord = selected[0];

  // System records stay visible and selectable so their values can be read, but
  // every write action against them is disabled.
  const selectionIsSystem = Boolean(selectedRecord?.is_system);

  // Edit acts on exactly one record; delete accepts many. The real console
  // behaves the same way — its Records tab is multi-select, its zone list is not.
  const singleSelection = selected.length === 1;
  const deletableSelection = selected.filter((record) => !record.is_system);
  const isBulk = deletableSelection.length > 1;

  // Narrow the chosen columns rather than replacing them, so a column the user
  // switched off stays off when the viewport grows again.
  const visibleColumns = isPhone
    ? state.visibleColumns.filter((column) => PHONE_COLUMNS.includes(column))
    : isCompact
      ? state.visibleColumns.filter((column) => TABLET_COLUMNS.includes(column))
      : state.visibleColumns;

  const columns: Column<RecordSetResponse>[] = [
    {
      id: 'name',
      header: 'Record name',
      sortable: true,
      isRowHeader: true,
      alwaysVisible: true,
      cell: (record) => (
        <span className="flex min-w-0 items-center gap-2">
          <span className="truncate font-medium text-ink">{record.name}</span>
          {record.is_system && (
            <Tooltip content="Generated by the zone and read-only">
              <span>
                <Badge tone="outline" size="sm" className="gap-1">
                  <Lock className="size-2.5" aria-hidden="true" />
                  System
                </Badge>
              </span>
            </Tooltip>
          )}
        </span>
      ),
    },
    {
      id: 'type',
      header: 'Type',
      sortable: true,
      shrink: true,
      cell: (record) => <RecordTypeBadge type={record.type} />,
    },
    {
      id: 'routing_policy',
      header: 'Routing policy',
      shrink: true,
      cell: (record) => <span className="text-ink-muted">{record.routing_policy}</span>,
    },
    {
      id: 'set_identifier',
      header: 'Differentiator',
      cell: (record) => record.set_identifier ?? <Dash />,
    },
    { id: 'alias', header: 'Alias', shrink: true, cell: () => <span className="text-ink-muted">No</span> },
    {
      id: 'values',
      header: 'Value/Route traffic to',
      cell: (record) => (
        // Values are untrusted text and render as text; React escapes them and
        // nothing here uses dangerouslySetInnerHTML.
        <div className="flex min-w-0 flex-col gap-0.5">
          {record.values.map((value, index) => (
            <code
              key={`${value}-${index}`}
              className="block truncate font-mono text-xs text-ink-secondary"
              title={value}
            >
              {value}
            </code>
          ))}
        </div>
      ),
    },
    {
      id: 'ttl',
      header: 'TTL',
      sortable: true,
      align: 'right',
      shrink: true,
      cell: (record) => <span className="text-ink-muted">{record.ttl}</span>,
    },
    { id: 'health_check', header: 'Health check ID', cell: () => <Dash /> },
    { id: 'evaluate_target_health', header: 'Evaluate target health', cell: () => <Dash /> },
    {
      id: 'id',
      header: 'Record ID',
      shrink: true,
      cell: (record) => (
        <code className="rounded border border-line bg-surface-inset px-1.5 py-0.5 text-xs text-ink-muted">
          {record.id}
        </code>
      ),
    },
  ];

  const hasFilters = Boolean(state.search) || Boolean(typeFilter);

  return (
    <>
      <DataTable<RecordSetResponse>
        items={records}
        columns={columns}
        visibleColumns={visibleColumns}
        getRowId={(record) => record.id}
        ariaLabel="DNS records"
        loading={query.isLoading}
        error={query.isError ? query.error : undefined}
        onRetry={() => void query.refetch()}
        skeletonRows={Math.min(state.pageSize, 8)}
        empty={
          hasFilters ? (
            <EmptyState
              variant="search"
              title="No matches"
              description="No record matches the current filter."
              action={
                <Button
                  onClick={() => {
                    state.setSearch('');
                    setTypeFilter('');
                  }}
                >
                  Clear filters
                </Button>
              }
            />
          ) : (
            <EmptyState
              variant="records"
              title="No records yet"
              description="Add a record to decide how traffic for this domain is routed."
              action={
                <Button variant="primary" onClick={() => setCreating(true)}>
                  <Plus aria-hidden="true" />
                  Create record
                </Button>
              }
              secondaryAction={
                <Button variant="secondary" onClick={() => setImporting(true)}>
                  <Upload aria-hidden="true" />
                  Import zone file
                </Button>
              }
            />
          )
        }
        sort={state.sort}
        order={state.order}
        onSortChange={state.setSorting}
        selectionMode="multi"
        selected={selected}
        onSelectionChange={setSelected}
        getRowLabel={(record) => `Select ${record.name} ${record.type}`}
        rowActions={(record) =>
          record.is_system
            ? []
            : [
                { id: 'edit', label: 'Edit record', icon: <Pencil /> },
                {
                  id: 'delete',
                  label: 'Delete record',
                  icon: <Trash2 />,
                  danger: true,
                  separatorBefore: true,
                },
              ]
        }
        onRowAction={(action, record) => {
          if (action === 'edit') setEditing(record);
          if (action === 'delete') setDeleting(record);
        }}
        page={state.page}
        pageSize={state.pageSize}
        total={total}
        onPageChange={state.setPage}
        onPageSizeChange={state.setPageSize}
        pageSizeOptions={[10, 25, 50]}
        itemNoun="records"
        onVisibleColumnsChange={state.setVisibleColumns}
        filters={
          <>
            <SearchInput
              value={state.search}
              onValueChange={state.setSearch}
              placeholder="Find records"
              aria-label="Filter records by name"
              countText={state.search && total ? `${total} matches` : undefined}
              containerClassName="w-full max-w-xs"
            />
            <Select
              // The empty string means "no filter" to the API, but an option
              // has to have a value the trigger can display — so `all` is the
              // sentinel in the control and is translated on the way out.
              value={typeFilter || 'all'}
              onValueChange={(value) => {
                setTypeFilter(value === 'all' ? '' : value);
                state.setPage(1);
              }}
              options={[
                { value: 'all', label: 'All types' },
                ...RECORD_TYPES.map((type) => ({ value: type, label: type })),
                { value: 'SOA', label: 'SOA' },
              ]}
              aria-label="Filter by record type"
              className="w-36"
            />
          </>
        }
        actions={
          <>
            {/* System records are read-only, so both write actions are disabled
                with the reason stated beneath the table rather than failing on
                submit. */}
            <Button
              variant="secondary"
              disabled={!singleSelection || selectionIsSystem}
              onClick={() => selectedRecord && setEditing(selectedRecord)}
              aria-label={
                selectionIsSystem
                  ? 'The zone’s generated records cannot be edited'
                  : 'Edit record'
              }
            >
              <Pencil aria-hidden="true" />
              <span className="hidden sm:inline">Edit</span>
            </Button>

            <Button
              variant="secondary"
              disabled={deletableSelection.length === 0}
              onClick={() => {
                if (isBulk) setBulkDeleting(true);
                else setDeleting(deletableSelection[0] ?? null);
              }}
              aria-label={
                selectionIsSystem && deletableSelection.length === 0
                  ? 'The zone’s generated SOA and NS records cannot be deleted'
                  : 'Delete records'
              }
            >
              <Trash2 aria-hidden="true" />
              <span className="hidden sm:inline">
                {isBulk ? `Delete (${deletableSelection.length})` : 'Delete'}
              </span>
            </Button>

            <Menu
              label="Import and export"
              items={[
                { id: 'import', label: 'Import from zone file', icon: <Upload /> },
                {
                  id: 'export-bind',
                  label: 'Export as BIND',
                  icon: <Download />,
                  separatorBefore: true,
                },
                { id: 'export-json', label: 'Export as JSON', icon: <FileUp /> },
              ]}
              onSelect={(id) => {
                if (id === 'import') setImporting(true);
                else {
                  void downloadZoneExport(
                    zone.id,
                    id === 'export-json' ? 'json' : 'bind',
                    zone.name,
                  );
                }
              }}
              trigger={
                <Button variant="secondary">
                  <Download aria-hidden="true" />
                  <span className="hidden sm:inline">Actions</span>
                </Button>
              }
            />

            <Button variant="primary" onClick={() => setCreating(true)}>
              <Plus aria-hidden="true" />
              <span className="hidden sm:inline">Create record</span>
            </Button>
          </>
        }
        footnote={
          selectionIsSystem && (
            <span className="flex items-start gap-1.5">
              <Lock className="mt-0.5 size-3.5 shrink-0 text-ink-faint" aria-hidden="true" />
              The zone&apos;s generated SOA and NS records are read-only. Deleting them would
              leave the zone unresolvable.
            </span>
          )
        }
      />

      <RecordFormPanel
        zone={zone}
        open={creating || editing !== null}
        record={editing}
        onClose={() => {
          setCreating(false);
          setEditing(null);
        }}
      />

      <DeleteRecordModal
        zoneId={zone.id}
        record={deleting}
        onClose={() => setDeleting(null)}
        onDeleted={() => setSelected([])}
      />

      <ImportZoneFileModal
        zoneId={zone.id}
        zoneName={zone.name}
        visible={importing}
        onClose={() => setImporting(false)}
      />

      <Modal
        open={bulkDeleting}
        onClose={() => setBulkDeleting(false)}
        busy={bulkDelete.isPending}
        tone="danger"
        icon={<Trash2 />}
        title={`Delete ${deletableSelection.length} records`}
        description="You cannot undo this action."
        footer={
          <>
            <Button
              variant="ghost"
              onClick={() => setBulkDeleting(false)}
              disabled={bulkDelete.isPending}
            >
              Cancel
            </Button>
            <Button
              variant="danger"
              loading={bulkDelete.isPending}
              onClick={async () => {
                await bulkDelete.mutateAsync(deletableSelection.map((record) => record.id));
                setSelected([]);
                setBulkDeleting(false);
              }}
            >
              Delete records
            </Button>
          </>
        }
      >
        <ul className="max-h-64 overflow-y-auto rounded-lg border border-line bg-surface-sunken p-1">
          {deletableSelection.map((record) => (
            <li
              key={record.id}
              className="flex items-center gap-2 rounded-md px-2 py-1.5 text-sm"
            >
              <RecordTypeBadge type={record.type} />
              <span className="truncate font-mono text-ink-secondary">{record.name}</span>
            </li>
          ))}
        </ul>
      </Modal>
    </>
  );
}

function Dash() {
  return (
    <span className="text-ink-faint" aria-label="Not set">
      –
    </span>
  );
}
